### ISSUE TITLE
feature request - multiple cluster with the same name

### ISSUE THREAD

**Issue by Simperdy** [bb-Ricardo/netbox-sync#119]
Hi Ricardo,

Netbox 3.1.0 finally allows [multiple datacenter, same cluster name](https://github.com/bb-Ricardo/netbox-sync/issues/39).
Could you modify your script to take advantage of this feature? ([Relax uniqueness constraint on cluster names](https://github.com/netbox-community/netbox/issues/1943))
The relation between the site/cluster group/cluster would make the cluster unique.

Example:

Site: vCenter1
Cluster Group: DC01
Cluster: CL01

Site: vCenter1
Cluster Group: DC02
Cluster: CL01

current behaviour: only one cluster with the name will be used and the other is "empty" in netbox.

best regards
Simperdy

**Comment by kinokocorp** [comment]
Hello,
I have the same problem as Simperdy. In vCenter, I have 7 datacenters with the same cluster name...
Bad practice, surely. But I don't manage this vCenter.

**Comment by bb-Ricardo** [comment]
I first have to figure out how to distinguish them within the script. and having a sample setup to actually test this.

**Comment by ftaeger** [comment]
Hi, I've got the same issue but maybe a bit less complex: I have two Clusters, both named "Cluster1" but they are on different sites and are imported by using two source configurations in settings.ini. 
I assumed the import would work per source config at least. But still - having multiple clusters being named the same way is not that uncommon. 

Futhermore someone might like to rename the cluster for convenience. 

If I understand it correctly, there might be the option to distinguish them by the cluster group as it seems there is one group per source? 

I'd be happy to assist here with a setup that's facing this issue since we're still building up Netbox there is some room for tests during the next days ;-)

**Comment by bb-Ricardo** [comment]
Hi @ftaeger, @Simperdy, @kinokocorp 

I just pushed another change. Can you test and see if it works now. You might have to change your config.
Check this change: https://github.com/bb-Ricardo/netbox-sync/commit/3e0532a25bc8f49d588dc911ba20eac77a69da7a#diff-e8853b390f2c8fcec0ba2e3d91a5ad304c96c6786b63a66ac3dfeb4232abcb7e

**Comment by christianahug** [comment]
Hey! This doesn't seem to be working quite yet. I have two clusters with the same name in different datacenters, but it won't sync the hosts for the cluster in the second datacenter. I've added the relation in the config file as dc1/cluster1 and dc2/cluster1.

**Comment by bb-Ricardo** [comment]
Mmhh, not so good.

Can you please post some DEBUG logs? You can get them by adding `-l DEBUG2`.

Thank you very much.

**Comment by bb-Ricardo** [comment]
Hi, I added a change to the 'development' branch to print the cluster group for a cluster as well. Can you see if this works better?

**Comment by christianahug** [comment]
Yup, that did the trick. Thanks for your llightning fast response time!

**Comment by bb-Ricardo** [comment]
thank you, Will close this issue

**Comment by deltabrav0** [comment]
I know this is closed, but I'm having same issue running the development release.

I have multiple clusters with the same name:  

TX01
    - CL01
    - CL02
    - CL03
IL01
- CL01

I have two vmware sources:  TX01 and IL01, TX01 is the first, IL01 is the second
Each source has the following stanza
cluster_site_relation = TX01/* = LFKNTXXA, IL01/* = MTONILXC

After discovery, there is no CL01 cluster in TX01 group.  I believe all the CL01 clusters get overwritten from the discovery of IL01 since it is the second source definition.

Am I missing something?
