### ISSUE TITLE
VMs are imported, even with vm_exclude_filter set

### ISSUE THREAD

**Issue by Houtek** [bb-Ricardo/netbox-sync#158]
Hi,
we have a cluster in a vCenter, where vmWare View/Horizon maschines are configured. Since they only run, when they are needed, I want to exclude them in the discovery and import. These vms are labeled with `XBVIEW[Number]`.
When the string "vm_exclude_filter" is filled only with the term `XBVIEW*`, the vms are excluded, I can see it with DEBUG2 while running in dry-mode.
But when the terms look like 
`vm_exclude_filter = XBVIEW*,XB-Entwickler*.*,MED-XBTEST*.*`
the vms named `XBVIEW` will be added to Netbox.
Do I have an error in my configuration?

**Comment by bb-Ricardo** [comment]
Hi,

I would suggest having a look at regular expressions in general. They are not trivial if you are unfamiliar with them.

because with RegEx `XBVIEW*` would match `XBVIEW` and `XBVIEWW` and `XBVIEWWWW` and so on. The asterisk behind a character stands for "0 or more occurrences of this character".

If you want to exclude all VMs which start with `XBVIEW` you need to add a `.`like this: `XBVIEW.*`. The `.` stands for ANY character in RegEx.

if you change your setting to:
```ini
vm_exclude_filter = XBVIEW.*,XB-Entwickler.*,MED-XBTEST.*
```

Then this should do the trick.

**Comment by Houtek** [comment]
Hi, 
thank you for looking into this.
It was my first thought, that I did something wrong with the regular expressions.
I changed the settings file with your hints and the VMs have been added to Netbox and the exclude filter didn't work as I expected it. I'll do another test with DEBUG2. Maybe there is something else which is still messed up.

**Comment by bb-Ricardo** [comment]
Did it help? Can I close the issue?

**Comment by Houtek** [comment]
No, it did not help. I still can only filter out XBVIEW.*, but not the others. 
Can I send you a debug file and you have a look into it?

**Comment by Houtek** [comment]
Hi,
I found out, that the reg ex `.*XB.*` works best for us to exclude all VMs with XB in the name. 
I discussed the issue with my colleagues and we decided that we only exclude the XBVIEW VMs. The reg ex `XBVIEW.*` works for us.
Thank you for your help.

**Comment by bb-Ricardo** [comment]
This sounds great. Glad it worked out.
