### ISSUE TITLE
Redfish and vcenter interface sync overlap

### ISSUE THREAD

**Issue by clementTal** [bb-Ricardo/netbox-sync#342]
When syncing redfish and vcenter sources, if interfaces exist in redfish but not in vcenter, like management interfaces (ilo), or interface exist in vcenter but not in redfish (virtual interfaces), missing interface are not sync but interfaces are overwrited (as describe here: https://github.com/bb-Ricardo/netbox-sync/blob/main/docs/common_concepts.md#try-to-match-current-netbox-object-device-vm-interfaces-to-discovered-ones)

An idea could be to add a parameter to add interface if mac address is not found instead of doing 1:1 match.

**Comment by bb-Ricardo** [comment]
Hi,

There might be conflicts with syncing interfaces. Would you be able to provide me a detailed example which describes the issue in detail? That would help a lot.

Thank you.

**Comment by bb-Ricardo** [comment]
Hi @clementTal,

sorry it took so long but finally got around looking into it. Found some issues with the redfish syncing. Also Interfaces will now be appended if not found in existing list of interfaces instead of overwriting them.

Can you please check out the `development` branch and see if it works better now.

**Comment by bb-Ricardo** [comment]
will close this as resolved. Please open a new issue if a similar issue occurs again.
