### ISSUE TITLE
multiple datacenter, same cluster name

### ISSUE THREAD

**Issue by Simperdy** [bb-Ricardo/netbox-sync#39]
I migrated from https://github.com/synackray/vcenter-netbox-sync and the sync worked perfectly.

the issue:
With the old sync but also with your sync, the hosts and vms in different datacenters but with the same cluster names are all assigned to the last discovered datacenter with the cluster name.

structure in vsphere:

DC01
- CL01
- CL03
- CL06

DC02
- CL01
- CL02

result in netbox:

DC01
- CL03
- CL06

DC02
- CL01
- CL02

in DC01 the CL01 is missing, instead all objects are assigned to DC02 --> CL01

**Comment by bb-Ricardo** [comment]
Ui, I have to look into it. It's definitely a bug which needs to fixed. Hope I got some time next week.

**Comment by Simperdy** [comment]
Maybe this is issue is netbox related and not a bug in your sync.
I tried to make a CL01 in DC01 manually but I got an error that a cluster with that name already exists.

Looks like you cant have two clusters with the same name in netbox. They seem to have no relation to the cluster groups.

**Comment by sdktr** [comment]
Might be worth an issue at the netbox repo, to ask for a name uniqueness constrain change

**Comment by bb-Ricardo** [comment]
Thanks for looking into this.

And yes, before we can sync it to NetBox this needs to be possible in NetBox first.

Or you rename your clusters to add a certain suffix? I know is is usually impossible 😕.

**Comment by bb-Ricardo** [comment]
Well, this NetBox issue will turn 3 years in march: https://github.com/netbox-community/netbox/issues/1943

Maybe everyone should add their 2 cents to the discussion to push the issue a bit up.

**Comment by JargeZ** [comment]
Hi I just ran into this same problem.
Is it possible as a workaround to use a prefix for the cluster name in, for example, from the source name?

**Comment by bb-Ricardo** [comment]
Hi

This should be possible. But needs quite some workaround.
* first implement a relation between datacenter and cluster
* if a cluster was found with the same name, rename the existing cluster and append the source in breakets to the cluster name.

How does this sound like?

**Comment by JargeZ** [comment]
Yes, this automatic bypass sounds correct.
The only thing that I have not yet deeply understood the project in order to be able to implement this behavior.

As a solution for myself, now I made such a patch with additional configuration:
![img](https://i.imgur.com/PJmdsdo.png)
I'll also change it to quotes, I'm not yet used to the fact that such symbols can be used :D

**Comment by bb-Ricardo** [comment]
First you need the relation so the code can distinguish these two instances of clusters.

And only after all sources are applied and before writing the data to NetBox we need a mitigation function to circumvent the NetBox limitations and rename clusters if necessary.

And once the problem is fixed in NetBox we could apply the function depending on the netbox API version.

What do you think?

**Comment by JargeZ** [comment]
Yes, now I'm in the process of understanding the work of the program and the fact that you need to add a bypass closer to the stage of interaction with the netbox sounds right. However, we need to add softening when getting objects and when saving.
If from netbox getted object is with the added name in brackets, then as I understand it, it will not be able to correctly associate with the cluster object from vmware

IMHO also, regarding the change in the netbox, it seems to me that this will be implemented with a small probability, because the name of the cluster should be semantically correct and in my view it should not overlap, but I have not seen enough use cases to judge unequivocally

**Comment by JargeZ** [comment]
Okay, I plan to change the get_display_name method in object_classes for the NBCluster class so that after calling the superclass it removes square brackets from the cluster name

And when creating an object, override the update method for the NBCluster call, and before calling the superclass, if it is not read_from_netbox, add the source name to the cluster name

I don’t think this is an elegant or even working solution, but all the time that I was studying the implementation of logic, I had these thoughts.
Perhaps it would be correct to do it through the secondary keys mechanism and inside the resolution of dependencies, but I have not yet reached this point and am writing my thoughts here to ask what you think.

**Comment by bb-Ricardo** [comment]
You are correct, I just ignored the fact that we need to parse the NetBox clusters again and need to "translate" them back.

Things are a bit wild right now at work. Hope to be able to fix this soon.

**Comment by bb-Ricardo** [comment]
Hi,

to be honest I didn't have too much time looking into it.

I also would propose to "upvote" the NetBox GitHub issue to actually support this behaviour. Then an adaption would be easy.

What do you think?

**Comment by Simperdy** [comment]
sure, lets hope they will include it in the near future. Our virtualisation team has the habit to name the clusters always the same. We got like 4 vcenter which always start with CL01
