### ISSUE TITLE
TypeError: argument of type 'NBSite' is not iterable

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#402]
Today I noticed that synchronization with vcenter does not work, 3 days ago everything was fine. I see such an error in the logs. Help please.

![image](https://github.com/bb-Ricardo/netbox-sync/assets/36307887/c03a69cb-5a0a-4a55-a0d2-5bdf1a384ed4)

Netbox 4
Sync 1.6

**Comment by bb-Ricardo** [comment]
Hi,

Good question. Was there any update regarding python version?

**Comment by ekrichbaum** [comment]
I just managed to duplicate this one and am running debug now to gather some info.  No updates to the OS, etc.

**Comment by ekrichbaum** [comment]
OK.  This is actually fairly evil. Create a site, slug, etc.  Change the name, but not the slug.  When the parser gets to the point of trying to create a site (that doesn't exist), it will fail because the slug does exist.

Cleanest easy answer is to fix the slug as well in the site to match the name.  Then a newly created site that doesn't match will create or the match would be proper.  In the meantime, I'll look at the error trapping there anyway.

**Comment by bb-Ricardo** [comment]
Hi, this is a great finding. Did not had this in mind but that is indeed a bit mean. Need to add a lookup for the slug if already used and generate a different slug if an object with generated slug already exists

**Comment by bb-Ricardo** [comment]
Hi @SerhiiZahuba and @ekrichbaum,

I added a mitigation for this issue with already used slugs to the `development` branch. would you be able to test if this is working now?

Thank you.
