### ISSUE TITLE
Proxmox adapter

### ISSUE THREAD

**Issue by n-rodriguez** [bb-Ricardo/netbox-sync#417]
Hi there!

Do you think it's possible to implement Proxmox adapter? A bit like https://github.com/bb-Ricardo/netbox-sync/pull/389

I can help to implement this, I just need some guidance about what needs to be implemented by child classes.

Thank you!

**Comment by bb-Ricardo** [comment]
Hi,

Help is always appreciated.

Sorry for the lack of documentation.

I'm not aware of which attributes can be requested from a proxmox instance. Otherwise just the same as VMware. The host details, as much as possible and VM details.

Have a look at the config class which defines the possible config options for the source and helps autogenerate the sample config file.

**Comment by bb-Ricardo** [comment]
Just seeing what https://github.com/bl4ko/netbox-ssot does and you should use this project to sync from Proxmox

**Comment by n-rodriguez** [comment]
> Just seeing what https://github.com/bl4ko/netbox-ssot does and you should use this project to sync from Proxmox

Yep, I'm thinking about totally moving to [netbox-ssot](https://github.com/bl4ko/netbox-ssot)

**Comment by bb-Ricardo** [comment]
It would actually be great if you would test a migration and report to netbox-ssot what exactly you are still missing.

**Comment by n-rodriguez** [comment]
> It would actually be great if you would test a migration and report to netbox-ssot what exactly you are still missing.

I'm working on it 👍 The main feature missing is tagging orphan items like you do with netbox-sync.

See: https://github.com/bl4ko/netbox-ssot/issues/148#issuecomment-2485683871
